/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as HotRouteImport } from './routes/hot'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as TokenTokenIdRouteImport } from './routes/token.$tokenId'
import { Route as CampaignsLeaderboardRouteImport } from './routes/campaigns.leaderboard'
import { Route as CampaignsAdminRouteImport } from './routes/campaigns.admin'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns.$campaignId'
import { Route as AuthSuccessRouteImport } from './routes/auth.success'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HotRoute = HotRouteImport.update({
  id: '/hot',
  path: '/hot',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignsRoute,
} as any)
const TokenTokenIdRoute = TokenTokenIdRouteImport.update({
  id: '/token/$tokenId',
  path: '/token/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsLeaderboardRoute = CampaignsLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => CampaignsRoute,
} as any)
const CampaignsAdminRoute = CampaignsAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => CampaignsRoute,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => CampaignsRoute,
} as any)
const AuthSuccessRoute = AuthSuccessRouteImport.update({
  id: '/auth/success',
  path: '/auth/success',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/challenges': typeof ChallengesRoute
  '/docs': typeof DocsRoute
  '/home': typeof HomeRoute
  '/hot': typeof HotRoute
  '/leaderboard': typeof LeaderboardRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/social': typeof SocialRoute
  '/terms': typeof TermsRoute
  '/auth/success': typeof AuthSuccessRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/campaigns/admin': typeof CampaignsAdminRoute
  '/campaigns/leaderboard': typeof CampaignsLeaderboardRoute
  '/token/$tokenId': typeof TokenTokenIdRoute
  '/campaigns/': typeof CampaignsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/challenges': typeof ChallengesRoute
  '/docs': typeof DocsRoute
  '/home': typeof HomeRoute
  '/hot': typeof HotRoute
  '/leaderboard': typeof LeaderboardRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/social': typeof SocialRoute
  '/terms': typeof TermsRoute
  '/auth/success': typeof AuthSuccessRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/campaigns/admin': typeof CampaignsAdminRoute
  '/campaigns/leaderboard': typeof CampaignsLeaderboardRoute
  '/token/$tokenId': typeof TokenTokenIdRoute
  '/campaigns': typeof CampaignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/challenges': typeof ChallengesRoute
  '/docs': typeof DocsRoute
  '/home': typeof HomeRoute
  '/hot': typeof HotRoute
  '/leaderboard': typeof LeaderboardRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/social': typeof SocialRoute
  '/terms': typeof TermsRoute
  '/auth/success': typeof AuthSuccessRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/campaigns/admin': typeof CampaignsAdminRoute
  '/campaigns/leaderboard': typeof CampaignsLeaderboardRoute
  '/token/$tokenId': typeof TokenTokenIdRoute
  '/campaigns/': typeof CampaignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/campaigns'
    | '/challenges'
    | '/docs'
    | '/home'
    | '/hot'
    | '/leaderboard'
    | '/privacy'
    | '/signin'
    | '/social'
    | '/terms'
    | '/auth/success'
    | '/campaigns/$campaignId'
    | '/campaigns/admin'
    | '/campaigns/leaderboard'
    | '/token/$tokenId'
    | '/campaigns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/challenges'
    | '/docs'
    | '/home'
    | '/hot'
    | '/leaderboard'
    | '/privacy'
    | '/signin'
    | '/social'
    | '/terms'
    | '/auth/success'
    | '/campaigns/$campaignId'
    | '/campaigns/admin'
    | '/campaigns/leaderboard'
    | '/token/$tokenId'
    | '/campaigns'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/campaigns'
    | '/challenges'
    | '/docs'
    | '/home'
    | '/hot'
    | '/leaderboard'
    | '/privacy'
    | '/signin'
    | '/social'
    | '/terms'
    | '/auth/success'
    | '/campaigns/$campaignId'
    | '/campaigns/admin'
    | '/campaigns/leaderboard'
    | '/token/$tokenId'
    | '/campaigns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CampaignsRoute: typeof CampaignsRouteWithChildren
  ChallengesRoute: typeof ChallengesRoute
  DocsRoute: typeof DocsRoute
  HomeRoute: typeof HomeRoute
  HotRoute: typeof HotRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PrivacyRoute: typeof PrivacyRoute
  SigninRoute: typeof SigninRoute
  SocialRoute: typeof SocialRoute
  TermsRoute: typeof TermsRoute
  AuthSuccessRoute: typeof AuthSuccessRoute
  TokenTokenIdRoute: typeof TokenTokenIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hot': {
      id: '/hot'
      path: '/hot'
      fullPath: '/hot'
      preLoaderRoute: typeof HotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/token/$tokenId': {
      id: '/token/$tokenId'
      path: '/token/$tokenId'
      fullPath: '/token/$tokenId'
      preLoaderRoute: typeof TokenTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/leaderboard': {
      id: '/campaigns/leaderboard'
      path: '/leaderboard'
      fullPath: '/campaigns/leaderboard'
      preLoaderRoute: typeof CampaignsLeaderboardRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/campaigns/admin': {
      id: '/campaigns/admin'
      path: '/admin'
      fullPath: '/campaigns/admin'
      preLoaderRoute: typeof CampaignsAdminRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/auth/success': {
      id: '/auth/success'
      path: '/auth/success'
      fullPath: '/auth/success'
      preLoaderRoute: typeof AuthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CampaignsRouteChildren {
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRoute
  CampaignsAdminRoute: typeof CampaignsAdminRoute
  CampaignsLeaderboardRoute: typeof CampaignsLeaderboardRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
}

const CampaignsRouteChildren: CampaignsRouteChildren = {
  CampaignsCampaignIdRoute: CampaignsCampaignIdRoute,
  CampaignsAdminRoute: CampaignsAdminRoute,
  CampaignsLeaderboardRoute: CampaignsLeaderboardRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
}

const CampaignsRouteWithChildren = CampaignsRoute._addFileChildren(
  CampaignsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CampaignsRoute: CampaignsRouteWithChildren,
  ChallengesRoute: ChallengesRoute,
  DocsRoute: DocsRoute,
  HomeRoute: HomeRoute,
  HotRoute: HotRoute,
  LeaderboardRoute: LeaderboardRoute,
  PrivacyRoute: PrivacyRoute,
  SigninRoute: SigninRoute,
  SocialRoute: SocialRoute,
  TermsRoute: TermsRoute,
  AuthSuccessRoute: AuthSuccessRoute,
  TokenTokenIdRoute: TokenTokenIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
